{
 "title": "Forecast Comparisons",
 "time": { "from": "now", "to": "now+14d" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "compare", "query": "48" },
   {
    "name": "location",
    "query": "show tag values on ecobee from forecast2 with key = \"location\""
   },
   {
    "name": "source",
    "query": "show tag values on ecobee from forecast2 with key = \"source\""
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "alias": "feels like",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "forecast2",
     "select": [
      [
       { "params": [ "feels_like" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$source$/" },
      { "condition": "AND", "key": "feels_like", "operator": ">", "value": "-50" }
     ]
    },
    {
     "alias": "temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "forecast2",
     "query": "SELECT mean(\"temperature\") FROM \"forecast\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$source$/" }
     ]
    },
    {
     "alias": "dewpoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "forecast2",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$source$/" }
     ]
    },
    {
     "alias": "actual temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE (\"deviceName\" = 'Craftown - Console') and '$location' = 'home' AND $timeFilter GROUP BY time($__interval), \"deviceName\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Craftown - Console" }
     ]
    },
    {
     "alias": "actual dewpoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dewPoint",
     "query": "SELECT mean(\"value\") FROM \"dewPoint\" WHERE $timeFilter and '$location' = 'home' GROUP BY time($__interval), \"deviceName\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "compare temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"temperature\") FROM \"forecast_history\".\"forecast_history2\" WHERE \"location\" = '$location' and \"source\" = '$source' and $timeFilter and \"forecast_time\" > $__from - $compare * 3600000 and \"forecast_time\" < $__from - ($compare * 3600000) + 3600000 GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "compare dewpoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"dewpoint\") FROM \"forecast_history\".\"forecast_history2\" WHERE \"location\" = '$location' and \"source\" = '$source' and $timeFilter and \"forecast_time\" > $__from - $compare * 3600000 and \"forecast_time\" < $__from - ($compare * 3600000) + 3600000 GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "actual feels like",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "feelsLike",
     "query": "SELECT mean(\"value\") FROM \"feelsLike\" WHERE (\"deviceName\" = 'Craftown - Console') AND '$location' = 'home' AND $timeFilter GROUP BY time($__interval), \"deviceName\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Craftown - Console" }
     ]
    },
    {
     "alias": "day",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "astronomy",
     "query": "SELECT mean(\"sun_up\") *-10 FROM \"astronomy\" WHERE (\"location\" =~ /^$location$/ AND \"source\" = 'visualcrossing') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "sun_up" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "visualcrossing" }
     ]
    }
   ]
  },
  {
   "title": "Precipitation, Cloud Cover",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "latest precip chance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "forecast2",
     "select": [
      [
       { "params": [ "precipitation_probability" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$source$/" }
     ]
    },
    {
     "alias": "latest precip rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "forecast2",
     "query": "SELECT max(\"precipIntensity\") FROM \"forecast\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "precipitation_amount" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$source$/" }
     ]
    },
    {
     "alias": "latest cloud cover",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "forecast2",
     "select": [
      [
       { "params": [ "sky_cover" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$source$/" }
     ]
    },
    {
     "alias": "compare cloud cover",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"sky_cover\") FROM \"forecast_history\".\"forecast_history2\" WHERE \"location\" = '$location' AND \"source\" = '$source' AND $timeFilter AND \"forecast_time\" > $__from - $compare * 3600000 and \"forecast_time\" < $__from - ($compare * 3600000) + 3600000 GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "compare precip rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"precipitation_amount\") FROM \"forecast_history\".\"forecast_history2\" WHERE \"location\" = '$location'AND \"source\" = '$source' AND $timeFilter AND \"forecast_time\" > $__from - $compare * 3600000 and \"forecast_time\" < $__from - ($compare * 3600000) + 3600000 GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "compare precip chance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"precipitation_probability\") FROM \"forecast_history\".\"forecast_history2\" WHERE \"location\" = '$location' AND \"source\" = '$source' AND $timeFilter AND \"forecast_time\" > $__from - $compare * 3600000 and \"forecast_time\" < $__from - ($compare * 3600000) + 3600000 GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "day",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "astronomy",
     "query": "SELECT mean(\"sun_up\") FROM \"astronomy\" WHERE (\"location\" =~ /^$location$/ AND \"source\" = 'visualcrossing') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "sun_up" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "visualcrossing" }
     ]
    }
   ]
  },
  {
   "title": "Accumulated Precipitation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "inches" }
   ],
   "targets": [
    {
     "alias": "latest accumulated precip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "forecast",
     "query": "SELECT cumulative_sum(max(\"precipitation_amount\")) FROM \"forecast2\" WHERE \"precipitation_probability\" > 0.2 and \"location\" = '$location' AND \"source\" = '$source' AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "precipIntensity" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    },
    {
     "alias": "compare accumulated precip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT cumulative_sum(max(\"precipitation_amount\")) FROM \"forecast_history\".\"forecast_history2\" WHERE \"precipitation_probability\" > 0.2 and \"location\" = '$location' and \"source\" = '$source' and $timeFilter and \"forecast_time\" > $__from - $compare * 3600000 and \"forecast_time\" < $__from - ($compare * 3600000) + 3600000 GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "actual accumulated precip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "monthlyrainin",
     "query": "SELECT cumulative_sum(non_negative_difference(max(\"value\"))) FROM \"monthlyrainin\" WHERE '$location' = 'home' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    },
    {
     "alias": "day",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"sun_up\") FROM \"astronomy\" WHERE (\"location\" =~ /^$location$/ AND \"source\" = 'visualcrossing') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "velocitymph" }
   ],
   "targets": [
    {
     "alias": "latest wind speed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "forecast2",
     "select": [
      [
       { "params": [ "wind_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$source$/" }
     ]
    },
    {
     "alias": "compare wind speed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"wind_speed\") FROM \"forecast_history\".\"forecast_history2\" WHERE \"location\" = '$location' and \"source\" = '$source' and $timeFilter and \"forecast_time\" > $__from - $compare * 3600000 and \"forecast_time\" < $__from - ($compare * 3600000) + 3600000 GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "day",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"sun_up\") *-10 FROM \"astronomy\" WHERE (\"location\" =~ /^$location$/ AND \"source\" = 'visualcrossing') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "actual gusts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "windgustmph",
     "query": "SELECT max(\"value\") FROM \"windgustmph\" WHERE '$location' = 'home' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind direction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "alias": "latest wind direction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "forecast2",
     "select": [
      [
       { "params": [ "wind_direction" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$source$/" }
     ]
    },
    {
     "alias": "compare wind direction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"wind_direction\") FROM \"forecast_history\".\"forecast_history2\" WHERE \"location\" = '$location' and $timeFilter and \"forecast_time\" > $__from - $compare * 3600000 and \"forecast_time\" < $__from - ($compare * 3600000) + 3600000 GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "day",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"sun_up\") FROM \"astronomy\" WHERE (\"location\" =~ /^$location$/ AND \"source\" = 'visualcrossing') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "actual",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "winddir",
     "query": "SELECT mean(\"value\") FROM \"winddir\" WHERE '$location' = 'home' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Moon",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "moon percent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "astronomy",
     "query": "SELECT max(\"full_moon_ratio\") FROM \"astronomy\" WHERE (\"location\" =~ /^$location$/ AND \"source\" = 'visualcrossing') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "full_moon_ratio" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "visualcrossing" }
     ]
    },
    {
     "alias": "moon",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "astronomy",
     "query": "SELECT mean(\"moon_up\") FROM \"astronomy\" WHERE (\"location\" =~ /^$location$/ AND \"source\" = 'theglobalweather') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "moon_up" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "visualcrossing" }
     ]
    },
    {
     "alias": "day",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"sun_up\") FROM \"astronomy\" WHERE (\"location\" =~ /^$location$/ AND \"source\" = 'visualcrossing') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}