{
 "title": "Forecast Comparisons VM",
 "time": { "from": "now-7d", "to": "now+7d" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "compare", "query": "48" },
   {
    "name": "location",
    "query": {
     "query": "label_values(forecast2_temperature, location)"
    }
   },
   {
    "name": "source",
    "query": {
     "query": "label_values(forecast2_temperature, source)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "expr": "WITH (\n    metric = forecast2_temperature{location=\"$location\",source=\"$source\"},\n    first(q) = limit_offset(1, 0, q),\n    future = first(sort_by_label_desc(metric, \"forecast_time\")),\n    past = first(sort_by_label(metric, \"forecast_time\")),\n)\navg(future, past)",
     "legendFormat": "temperature"
    },
    {
     "expr": "WITH (\n    metric = forecast2_dewpoint{location=\"$location\",source=\"$source\"},\n    first(q) = limit_offset(1, 0, q),\n    future = first(sort_by_label_desc(metric, \"forecast_time\")),\n    past = first(sort_by_label(metric, \"forecast_time\")),\n)\navg(future, past)",
     "legendFormat": "dewpoint"
    },
    {
     "expr": "WITH (\n    metric = forecast2_feels_like{location=\"$location\",source=\"$source\"},\n    first(q) = limit_offset(1, 0, q),\n    future = first(sort_by_label_desc(metric, \"forecast_time\")),\n    past = first(sort_by_label(metric, \"forecast_time\")),\n)\navg(future, past) > -100",
     "legendFormat": "feels like"
    },
    {
     "expr": "temperature{sensor=\"outdoor\"}",
     "legendFormat": "actual temperature"
    },
    {
     "expr": "temperature{sensor=\"dewpoint\"}",
     "legendFormat": "actual dewpoint"
    },
    {
     "expr": "temperature{sensor=\"feelsLike\"}",
     "legendFormat": "actual feels like"
    },
    {
     "expr": "astronomy_sun_up{location=\"$location\",source=\"visualcrossing\"}",
     "legendFormat": "day"
    },
    {
     "expr": "WITH (\n    metric = forecast2_temperature{location=\"$location\",source=\"$source\"},\n    nth(q, n) = limit_offset(1, n, q),\n)\nnth(sort_by_label_desc(metric, \"forecast_time\"), $compare)",
     "legendFormat": "compare temperature"
    },
    {
     "expr": "WITH (\n    metric = forecast2_dewpoint{location=\"$location\",source=\"$source\"},\n    nth(q, n) = limit_offset(1, n, q),\n)\nnth(sort_by_label_desc(metric, \"forecast_time\"), $compare)",
     "legendFormat": "compare dewpoint"
    }
   ]
  },
  {
   "title": "Precipitation, Cloud Cover",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "WITH (\n    metric = forecast2_precipitation_probability{location=\"$location\",source=\"$source\"},\n    first(q) = limit_offset(1, 0, q),\n    future = first(sort_by_label_desc(metric, \"forecast_time\")),\n    past = first(sort_by_label(metric, \"forecast_time\")),\n)\navg(future, past)",
     "legendFormat": "latest precip chance"
    },
    {
     "expr": "WITH (\n    metric = forecast2_precipitation_amount{location=\"$location\",source=\"$source\"},\n    first(q) = limit_offset(1, 0, q),\n    future = first(sort_by_label_desc(metric, \"forecast_time\")),\n    past = first(sort_by_label(metric, \"forecast_time\")),\n)\navg(future, past)",
     "legendFormat": "latest precip rate"
    },
    {
     "expr": "WITH (\n    metric = forecast2_sky_cover{location=\"$location\",source=\"$source\"},\n    first(q) = limit_offset(1, 0, q),\n    future = first(sort_by_label_desc(metric, \"forecast_time\")),\n    past = first(sort_by_label(metric, \"forecast_time\")),\n)\navg(future, past)",
     "legendFormat": "latest cloud cover"
    },
    {
     "expr": "astronomy_sun_up{location=\"$location\",source=\"visualcrossing\"}",
     "legendFormat": "day"
    },
    {
     "expr": "WITH (\n    metric = forecast2_precipitation_probability{location=\"$location\",source=\"$source\"},\n    nth(q, n) = limit_offset(1, n, q),\n)\nnth(sort_by_label_desc(metric, \"forecast_time\"), $compare)",
     "legendFormat": "compare precip chance"
    },
    {
     "expr": "WITH (\n    metric = forecast2_precipitation_amount{location=\"$location\",source=\"$source\"},\n    nth(q, n) = limit_offset(1, n, q),\n)\nnth(sort_by_label_desc(metric, \"forecast_time\"), $compare)",
     "legendFormat": "compare precip rate"
    },
    {
     "expr": "WITH (\n    metric = forecast2_sky_cover{location=\"$location\",source=\"$source\"},\n    nth(q, n) = limit_offset(1, n, q),\n)\nnth(sort_by_label_desc(metric, \"forecast_time\"), $compare)",
     "legendFormat": "compare cloud cover"
    },
    {
     "expr": "WITH (\n    metric = forecast2_snow_amount{location=\"$location\",source=\"$source\"},\n    first(q) = limit_offset(1, 0, q),\n    future = first(sort_by_label_desc(metric, \"forecast_time\")),\n    past = first(sort_by_label(metric, \"forecast_time\")),\n)\navg(future, past)",
     "legendFormat": "latest snow rate"
    }
   ]
  },
  {
   "title": "Accumulated Precipitation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "inches" }
   ],
   "targets": [
    {
     "expr": "WITH (\n    labels = {location=\"$location\",source=\"$source\"},\n    amount = forecast2_precipitation_amount{labels},\n    prob = forecast2_precipitation_probability{labels},\n    first(q) = limit_offset(1, 0, q),\n    future(q) = first(sort_by_label_desc(q, \"forecast_time\")),\n    past(q) = first(sort_by_label(q, \"forecast_time\")),\n)\n# sum_over_time((avg(past(amount), future(amount)) unless avg(past(prob), future(prob)) < 0.2)[$__range:1h])\n# running_sum(avg(past(amount), future(amount)) unless avg(past(prob), future(prob)) < 0.2)\nrunning_sum(avg(past(amount), future(amount)))",
     "legendFormat": "latest accumulated precip"
    },
    {
     "expr": "WITH (\n    summed = remove_resets(rain_in{period=\"monthly\"}[$__range]),\n)\nsummed - range_first(summed)",
     "legendFormat": "actual accumulated precip"
    },
    {
     "expr": "astronomy_sun_up{location=\"$location\",source=\"visualcrossing\"}",
     "legendFormat": "day"
    },
    {
     "expr": "WITH (\n    labels = {location=\"$location\",source=\"$source\"},\n    amount = forecast2_precipitation_amount{labels},\n    prob = forecast2_precipitation_probability{labels},\n    nth_sorted(q) = limit_offset(1, $compare, sort_by_label_desc(q, \"forecast_time\")),\n\n)\nsum_over_time((nth_sorted(amount) unless nth_sorted(prob) < 0.2)[$__range:1h])",
     "legendFormat": "compare accumulated precip"
    }
   ]
  },
  {
   "title": "Wind speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "velocitymph" }
   ],
   "targets": [
    {
     "expr": "WITH (\n    metric = forecast2_wind_speed{location=\"$location\",source=\"$source\"},\n    first(q) = limit_offset(1, 0, q),\n    future = first(sort_by_label_desc(metric, \"forecast_time\")),\n    past = first(sort_by_label(metric, \"forecast_time\")),\n)\navg(future, past)",
     "legendFormat": "latest wind speed"
    },
    {
     "expr": "wind_speed_mph{type=\"gusts\"}",
     "legendFormat": "actual gusts"
    },
    {
     "expr": "astronomy_sun_up{location=\"$location\",source=\"visualcrossing\"} * -10",
     "legendFormat": "day"
    },
    {
     "expr": "WITH (\n    metric = forecast2_wind_speed{location=\"$location\",source=\"$source\"},\n    nth(q, n) = limit_offset(1, n, q),\n)\nnth(sort_by_label_desc(metric, \"forecast_time\"), $compare)",
     "legendFormat": "compare wind speed"
    }
   ]
  },
  {
   "title": "Wind direction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "expr": "WITH (\n    metric = forecast2_wind_direction{location=\"$location\",source=\"$source\"},\n    first(q) = limit_offset(1, 0, q),\n    future = first(sort_by_label_desc(metric, \"forecast_time\")),\n    past = first(sort_by_label(metric, \"forecast_time\")),\n)\navg(future, past)",
     "legendFormat": "latest wind direction"
    },
    { "expr": "wind_dir", "legendFormat": "{{name}}" },
    {
     "expr": "astronomy_sun_up{location=\"$location\",source=\"visualcrossing\"}",
     "legendFormat": "day"
    },
    {
     "expr": "WITH (\n    metric = forecast2_wind_direction{location=\"$location\",source=\"$source\"},\n    nth(q, n) = limit_offset(1, n, q),\n)\nnth(sort_by_label_desc(metric, \"forecast_time\"), $compare)",
     "legendFormat": "compare wind direction"
    }
   ]
  },
  {
   "title": "Moon",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "WITH (\n    metric = astronomy_full_moon_ratio{location=\"$location\",source=\"visualcrossing\"},\n    first(q) = limit_offset(1, 0, q),\n    future = first(sort_by_label_desc(metric, \"forecast_time\")),\n    past = first(sort_by_label(metric, \"forecast_time\")),\n)\navg(future, past)",
     "legendFormat": "moon percent"
    },
    {
     "expr": "astronomy_sun_up{location=\"$location\",source=\"visualcrossing\"}",
     "legendFormat": "day"
    }
   ]
  }
 ]
}