name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    uses: tedpearson/ForecastMetrics/.github/workflows/release-template.yaml@master
    with:
      executable: forecastmetrics
      ref: master